-- Create a custom type for booking status for better data integrity
CREATE TYPE booking_status AS ENUM ('pending', 'accepted', 'completed');

-- Create the bookings table
CREATE TABLE bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    pickup_address text,
    dropoff_address text,
    pickup_coords jsonb,
    dropoff_coords jsonb,
    vehicle_type text,
    price numeric,
    status booking_status DEFAULT 'pending'
);

-- Enable Row Level Security (RLS) for the bookings table
-- This is a crucial security measure to ensure users can only access their own data.
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- 1. Allow users to select (read) their own bookings.
CREATE POLICY "Users can view their own bookings"
ON bookings FOR SELECT
USING (auth.uid() = user_id);

-- 2. Allow users to insert (create) new bookings for themselves.
CREATE POLICY "Users can create new bookings"
ON bookings FOR INSERT
WITH CHECK (auth.uid() = user_id);
