
CREATE TABLE public.user_saved_addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL, -- Corresponds to session.user.email
    label text NOT NULL, -- "Home", "Work", or a custom label
    address_text text NOT NULL,
    coordinates jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
